name: Pull Request

on: pull_request

jobs:
  check:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.13
        uses: actions/setup-node@v3
        with:
          node-version: 16.13
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - uses: actions/cache@v3
        id: eslint-cache
        with:
          path: |
            .eslintcache
            tsconfig.tsbuildinfo
          key: ${{ matrix.os }}-eslint-tsbuildinfo-${{ hashFiles('**/*.ts','**/*.js', 'package.json', 'tsconfig.json') }}

      - name: Install workerd Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y libc++1

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check for errors
        run: npm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

  schema:
    if: ${{ github.repository_owner == 'cloudflare' }}
    name: "Publish JSON schema"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install workerd Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y libc++1

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build Wrangler
        run: npm run build

      - name: Generate JSON schema
        run: npx typescript-json-schema packages/wrangler/tsconfig.json RawConfig > packages/json-schema-worker/wrangler-schema.json

      - name: Upload JSON schema
        run: npx wrangler kv:key put ${{ github.head_ref }} --path wrangler-schema.json --binding Schema --preview false
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        working-directory: packages/json-schema-worker

      - name: Build & Publish JSON Schema worker
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        working-directory: packages/json-schema-worker

  test:
    name: "Tests"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.13
        uses: actions/setup-node@v3
        with:
          node-version: 16.13
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install workerd Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y libc++1

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run builds
        run: npm run build
        env:
          NODE_ENV: "production"

      - name: Run tests & collect coverage
        run: npm run test:ci
        env:
          TMP_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TMP_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Report Code Coverage
        uses: codecov/codecov-action@v3
